services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eduflow
      MYSQL_USER: eduflow
      MYSQL_PASSWORD: eduflow
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d:ro
    ports:
      - "3310:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ../backend
    env_file:
      - ../backend/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3002:3001"

  frontend:
    build: ..
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db-data:
